### ISSUE TITLE
Calling 'devel' blocks in formulae is disabled

### ISSUE THREAD

**Issue by tkx68** [octave-app/homebrew-octave-app-blas#2]
Doing `brew tap octave-app/octave-app-blas` on my macbook running macOS 10.15.7 (catalina) I get the following error message:

`==> Tapping octave-app/octave-app-blas
Cloning into '/usr/local/Homebrew/Library/Taps/octave-app/homebrew-octave-app-blas'...
remote: Enumerating objects: 423, done.
remote: Total 423 (delta 0), reused 0 (delta 0), pack-reused 423
Receiving objects: 100% (423/423), 85.45 KiB | 1.50 MiB/s, done.
Resolving deltas: 100% (258/258), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/octave-app/homebrew-octave-app-blas/Formula/atlas.rb
atlas: Calling 'devel' blocks in formulae is disabled! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the octave-app/octave-app-blas tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/octave-app/homebrew-octave-app-blas/Formula/atlas.rb:7

Error: Cannot tap octave-app/octave-app-blas: invalid syntax in tap!`

I use the following brew version:

`Homebrew 2.5.2
Homebrew/homebrew-core (git revision 0b654; last commit 2020-09-29)
Homebrew/homebrew-cask (git revision be3785; last commit 2020-09-29)`

**Comment by apjanke** [comment]
Fixed in https://github.com/octave-app/homebrew-octave-app-blas/commit/c5d95800a0a2a226ba8e330ccb8ae8e5fdd110d4 by removing the `devel` block in the `atlas` formula.

Thanks for the bug report!
